### ISSUE TITLE
Add flag to unlock a monitor or setting when editing

### ISSUE THREAD

**Issue by hierynomus** [StackVista/stackstate-cli#8]
### Problem
Currently when you try to edit a monitor from a StackPack, StackState will return the following error to the CLI:

```
STS CLI 2 $ EDITOR=vi go run main.go monitor edit --id 43848310532357
❌ 428 Precondition Required
_type: ErrorsResponse
errors:
  - _type: NodesLockedError
    errorCode: 4044
    message: Nodes locked from modification/deletion.
    nodeNames:
      - Monitor:Too many full table scans
serverTimestamp: 1.66392588233e+12
trackingKey: 43por071ehj0tkvdosl9q4impp
```

In the UI there is a way to "enforce" such an edit by unlocking the node first.

### Solution
Add a flag to the `MonitorEdit` and `SettingsEdit` CLI commands that unlocks the node if:

- The content of the node differs after the edit
- The node in question is locked

Name the flag:

- `--unlock` -- Unlocks the monitor before saving it if needed

Extend the `Long` description of the command with:

```
When '--unlock' is specified, the CLI will always unlock the Monitor when editing it. This might introduce changes that prevent the originating StackPack from upgrading correctly. Any changes you make are not the responsibility of the StackPack developer.
```
